# !WARNING: MANUAL ACTION REQUIRED!

# You must keep these file in sync:
# - `tools/deployment/cli/production/config.yaml` -- CONFIG ONLY
# - `tools/deployment/cli/staging/config.yaml` -- CONFIG ONLY
# - `tools/deployment/cli/testing/config.yaml` -- CONFIG ONLY
# - `apps/cli/.env.example` -- CONFIG & SECRETS
# - `apps/cli/src/_services/env/keys.ts` -- CONFIG & SECRETS

apiVersion: v1
kind: ConfigMap
metadata:
  name: biodiversity-cli-config
  namespace: staging
data:
  ## Config
  BIO_ENVIRONMENT: staging

  IUCN_BASE_URL: https://apiv3.iucnredlist.org/api/v3

  WIKI_BASE_URL: https://en.wikipedia.org
  WIKI_MEDIA_BASE_URL: https://www.mediawiki.org
  ARBIMON_BASE_URL: https://arbimon.rfcx.org
  MEDIA_API_BASE_URL: https://media-api.rfcx.org

  AWS_S3_BUCKET_REGION: eu-west-1
  AWS_S3_BUCKET_NAME: arbimon-exports
