version: "3.2"
services:
  timescaledb-test:
    image: "timescale/timescaledb:latest-pg12"
    ports:
      - "5434:5432"
    volumes:
      - data-timescaledb-test:/var/lib/postgresql/data
      - ./init.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
    command: "-c max_connections=200"
volumes:
  data-timescaledb-test:
